/**
 * Static initial data for client-safe usage.
 * This file must NOT import any server-only modules (mongoose, jwt, etc.)
 * It is safe to import from client components.
 */

import type { ICategory, IMenuItem, IPromo, ISettings } from './types';

export const STATIC_CATEGORIES: ICategory[] = [
  { id: 'cat-1', _id: 'cat-1', name: 'Semua Menu', slug: 'semua', sortOrder: 0 },
  { id: 'cat-2', _id: 'cat-2', name: 'Makanan Utama', slug: 'makanan', sortOrder: 1 },
  { id: 'cat-3', _id: 'cat-3', name: 'Minuman', slug: 'minuman', sortOrder: 2 },
  { id: 'cat-4', _id: 'cat-4', name: 'Cemilan', slug: 'cemilan', sortOrder: 3 },
  { id: 'cat-5', _id: 'cat-5', name: 'Dessert', slug: 'dessert', sortOrder: 4 },
];

export const STATIC_MENU_ITEMS: IMenuItem[] = [
  {
    id: 'item-1', _id: 'item-1',
    name: 'Nasi Goreng Spesial',
    description: 'Wok-fried rice with secret heritage spices, sunny egg, and chicken satay',
    price: 45000,
    category: 'makanan',
    photoUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
    badge: 'best_seller',
    spiceLevels: [
      { label: 'Tidak Pedas', priceModifier: 0 },
      { label: 'Sedang', priceModifier: 0 },
      { label: 'Pedas', priceModifier: 0 },
    ],
    addOns: [
      { label: 'Ekstra Telur', price: 5000 },
      { label: 'Ekstra Ayam', price: 10000 },
      { label: 'Ekstra Sambal Ulek', price: 3000 },
    ],
    isActive: true,
  },
  {
    id: 'item-2', _id: 'item-2',
    name: 'Sate Ayam Madura',
    description: 'Char-grilled chicken skewers smothered in rich, sweet peanut sauce',
    price: 38000,
    category: 'makanan',
    photoUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    badge: 'best_seller',
    spiceLevels: [
      { label: 'Tidak Pedas', priceModifier: 0 },
      { label: 'Sedang', priceModifier: 0 },
      { label: 'Pedas', priceModifier: 0 },
    ],
    addOns: [
      { label: 'Ekstra Bumbu Kacang', price: 4000 },
      { label: 'Ekstra Lontong', price: 5000 },
    ],
    isActive: true,
  },
  {
    id: 'item-3', _id: 'item-3',
    name: 'Soto Ayam Ambengan',
    description: 'Clear, aromatic yellow chicken soup served with koya powder',
    price: 35000,
    category: 'makanan',
    photoUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80',
    badge: 'chefs_choice',
    spiceLevels: [
      { label: 'Tidak Pedas', priceModifier: 0 },
      { label: 'Sedang', priceModifier: 0 },
      { label: 'Pedas', priceModifier: 0 },
    ],
    addOns: [
      { label: 'Ekstra Koya', price: 3000 },
      { label: 'Ekstra Telur Rebus', price: 5000 },
    ],
    isActive: true,
  },
  {
    id: 'item-4', _id: 'item-4',
    name: 'Es Teh Manis',
    description: 'Signature brewed black tea served chilled with pure cane sugar',
    price: 12000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    badge: 'none',
    spiceLevels: [],
    addOns: [
      { label: 'Less Sugar', price: 0 },
      { label: 'Ekstra Lemon', price: 3000 },
    ],
    isActive: true,
  },
  {
    id: 'item-5', _id: 'item-5',
    name: 'Gado-Gado Batavia',
    description: 'Mixed vegetable salad with classic peanut sauce and crackers',
    price: 32000,
    category: 'makanan',
    photoUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    badge: 'vegan_friendly',
    spiceLevels: [
      { label: 'Tidak Pedas', priceModifier: 0 },
      { label: 'Sedang', priceModifier: 0 },
      { label: 'Pedas', priceModifier: 0 },
    ],
    addOns: [
      { label: 'Ekstra Kerupuk', price: 3000 },
      { label: 'Ekstra Telur', price: 5000 },
    ],
    isActive: true,
  },
  {
    id: 'item-6', _id: 'item-6',
    name: 'Rendang Daging Sapi',
    description: 'Slow-cooked beef in rich coconut milk and signature spices',
    price: 55000,
    category: 'makanan',
    photoUrl: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80',
    badge: 'none',
    spiceLevels: [
      { label: 'Tidak Pedas', priceModifier: 0 },
      { label: 'Sedang', priceModifier: 0 },
      { label: 'Pedas', priceModifier: 0 },
    ],
    addOns: [{ label: 'Nasi Putih Warm', price: 6000 }],
    isActive: true,
  },
  {
    id: 'item-7', _id: 'item-7',
    name: 'Pisang Goreng Madu',
    description: 'Crispy honey-glazed banana fritters, a perfect sweet ending',
    price: 22000,
    category: 'dessert',
    photoUrl: 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=800&q=80',
    badge: 'none',
    spiceLevels: [],
    addOns: [
      { label: 'Ekstra Keju', price: 5000 },
      { label: 'Cokelat Meeres', price: 4000 },
    ],
    isActive: true,
  },
  {
    id: 'item-8', _id: 'item-8',
    name: 'Es Kopi Senja',
    description: 'Double espresso susu gula aren kental racikan istimewa warkop',
    price: 18000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    badge: 'best_seller',
    spiceLevels: [],
    addOns: [
      { label: 'Less Sugar', price: 0 },
      { label: 'Extra Shot Espresso', price: 5000 },
      { label: 'Oat Milk Sub', price: 6000 },
    ],
    isActive: true,
  },
  {
    id: 'item-9', _id: 'item-9',
    name: 'Cappuccino Klasik',
    description: 'Espresso klasik dengan foam lembut dan taburan cocoa pilihan',
    price: 22000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    badge: 'kopi',
    spiceLevels: [],
    addOns: [
      { label: 'Extra Cocoa Powder', price: 2000 },
      { label: 'Vanilla Syrup', price: 4000 },
    ],
    isActive: true,
  },
  {
    id: 'item-10', _id: 'item-10',
    name: 'Matcha Latte',
    description: 'Pure uji matcha berpadu susu segar gurih creamy',
    price: 24000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    badge: 'non-coffee',
    spiceLevels: [],
    addOns: [
      { label: 'Less Sugar', price: 0 },
      { label: 'Soy Milk Sub', price: 5000 },
    ],
    isActive: true,
  },
  {
    id: 'item-11', _id: 'item-11',
    name: 'Croissant Almond',
    description: 'Flaky renyah lapis butter dengan limpahan roasted almond gurih',
    price: 26000,
    category: 'cemilan',
    photoUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    badge: 'pastry',
    spiceLevels: [],
    addOns: [
      { label: 'Hangatkan (Warm up)', price: 0 },
      { label: 'Ekstra Honey Butter', price: 3000 },
    ],
    isActive: true,
  },
  {
    id: 'item-12', _id: 'item-12',
    name: 'V60 Senja Reserve',
    description: 'Single origin arabika pilihan dengan aroma floral dan fruity',
    price: 28000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    badge: 'signature',
    spiceLevels: [],
    addOns: [
      { label: 'Ice Drip Mode', price: 2000 },
      { label: 'Biji Kopi Gayo Honey', price: 4000 },
    ],
    isActive: true,
  },
  {
    id: 'item-13', _id: 'item-13',
    name: 'Caramel Macchiato',
    description: 'Espresso lembut dengan saus karamel madu dan susu velvety',
    price: 26000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',
    badge: 'favorite',
    spiceLevels: [],
    addOns: [
      { label: 'Extra Caramel Drizzle', price: 3000 },
      { label: 'Whipped Cream', price: 4000 },
    ],
    isActive: true,
  },
  {
    id: 'item-14', _id: 'item-14',
    name: 'Cold Brew Citrus',
    description: 'Slow-steeped cold brew 18 jam dengan sentuhan kesegaran citrus',
    price: 25000,
    category: 'minuman',
    photoUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    badge: 'refreshing',
    spiceLevels: [],
    addOns: [
      { label: 'Extra Citrus Wedge', price: 2000 },
    ],
    isActive: true,
  },
  {
    id: 'item-15', _id: 'item-15',
    name: 'Pain Au Chocolat',
    description: 'Pastry lapis butter renyah dengan isian dark chocolate Belgia lumer',
    price: 24000,
    category: 'cemilan',
    photoUrl: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=800&q=80',
    badge: 'artisan',
    spiceLevels: [],
    addOns: [
      { label: 'Hangatkan (Warm up)', price: 0 },
    ],
    isActive: true,
  },
  {
    id: 'item-16', _id: 'item-16',
    name: 'Paket Semangat Pagi',
    description: 'Kopi Senja + Butter Croissant',
    price: 32000,
    category: 'paket',
    photoUrl: 'https://images.unsplash.com/photo-1509785307050-d4066910ec1e?auto=format&fit=crop&w=400&q=80',
    badge: 'chefs_choice',
    spiceLevels: [],
    addOns: [],
    isActive: true,
  },
  {
    id: 'item-17', _id: 'item-17',
    name: 'Paket Teman Kerja',
    description: '2x Kopi Senja + Snack Mix',
    price: 55000,
    category: 'paket',
    photoUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=400&q=80',
    badge: 'chefs_choice',
    spiceLevels: [],
    addOns: [],
    isActive: true,
  },
  {
    id: 'item-18', _id: 'item-18',
    name: 'Paket Sore Santai',
    description: 'Matcha Latte + Pain Au Chocolat',
    price: 38000,
    category: 'paket',
    photoUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
    badge: 'chefs_choice',
    spiceLevels: [],
    addOns: [],
    isActive: true,
  },
];

export const STATIC_PROMOS: IPromo[] = [
  {
    id: 'promo-1', _id: 'promo-1',
    title: 'Paket Hemat! Ayam + Lalapan + Es Teh',
    description:
      'Yuk, sekalian pesan paket hemat untuk keluarga di rumah agar santap makan lebih lengkap dan meriah!',
    originalPrice: 40000,
    discountedPrice: 30000,
    isActive: true,
  },
];

export const STATIC_SETTINGS: ISettings = {
  taxRatePercent: 10,
  serviceChargeRatePercent: 5,
  restaurantInfo: {
    name: 'Warkop Betawa',
    address: 'Jl. Nusantara No. 14, Jakarta',
    whatsapp: '+6281234567890',
    instagram: '@selerasambal',
    email: 'halo@selerasambal.id',
  },
};
